//{{{
{
	"revision": 1,
	"permissions": [],
	"creator": "GUEST",
	"modifier": "GUEST",
	"created": "20100202134520",
	"modified": "20100202134520",
	"recipe": "default",
	"bag": "common",
	"type": "None",

	"title": "Job ID",
	"text": "",
	"tags": [],
	"fields": {
		"tasktypeds.taskcategory": "R",
		"tasktypeds.tasktypeid": "R1",
		"tasktypeds.skilldurationds.skillcode": "RFJBAS",
		"tasktypeds.skilldurationds.duration": "95",
		"tasktypeds.skilldurationds.numberofpeople": "1",
		"businessassetidcode": "CNP/UD",
		"mainworklocation": "LN",
		"responsecode": "NONE",
		"postcode": "SO427GX",
		"workaddressds.worklocationqualifier": "C",
		"workaddressds.addressline": "Tinoil\nBartle Road\nWoodlands\nSouthampton\nHampshire",
		"workaddressds.contactname": "PSTN HELP",
		"workaddressds.contactphoneno": "800151",
		"workaddressds.addresspostcode": "SO427GX",
		"tasknotesds.@1.notetype": "HAZ",
		"tasknotesds.@1.notetext": "CP:None**********CP:None**********CP:None**********CP: \nCP:None**********CP:None**********CP:None**********CP: \nCP:\nNo further hazards are present for this task               \n",
		"tasknotesds.@1.noteappendind": "FALSE",
		"tasknotesds.@2.notetype": "WAR",
		"tasknotesds.@2.notetext": "ARTISAN: Exch Code-ST-CADNM DP Id- 284, SUB POLE-00: 511:: \n Low Drop Wire on BT provided / owned Pole:: \n ORIGINATING_DATE-29-AUG-07:: REMEDY-320\n PRM: Exch Code-ST-CADNM DP Id- 284: site of special \nscientific interest  high load\nNote:Historic records show this location is in a cautionary\narea. Contact your planning team if there are no details \nabout this hazardous area.\nNo further warnings are present for this task              \n",
		"tasknotesds.@2.noteappendind": "FALSE",
		"terminationds.@1.nodeid": "284",
		"terminationds.@1.nodecat": "D",
		"terminationds.@1.terminationno": "3",
		"terminationds.@1.nodeside": "E",
		"terminationds.@2.nodeid": "7",
		"terminationds.@2.nodecat": "P",
		"terminationds.@2.terminationno": "393",
		"terminationds.@2.nodeside": "D"
	}
};
//}}}
